services:
  chatfe:
    restart: always
    networks:
      - common
    build: 
      context: ./client
      dockerfile: dockerfile.reactUI
    image: trankhoi/chatapp-sernstack:chatclientfe
    ports:
      - "3000:3000"
    environment:
      # -  REACT_APP_SERVER_URL=http://localhost:5000
      -  REACT_APP_USER_SERVICE=http://localhost:80
      -  REACT_APP_CHAT_SERVICE=http://localhost:80
      -  REACT_APP_MESSAGE_SERVICE=http://localhost:80
    depends_on:
      - mysqldb
      - redisdb
      - chatuserbe
      - chatchatbe
      - chatmessagebe

  chatuserbe: 
    restart: always
    build: 
      context: ./userService
      dockerfile: dockerfile.node
    image: trankhoi/chatapp-sernstack:chatuserbe
    environment:
      -  MYSQL_HOST=mysqldb
      -  MYSQL_PORT=3306
      -  NODE_ENV=development
      -  PORT = 5000

      -  JWT_ACTIVE_TOKEN=)@n!ZE3AD6g$q&m7%KUXZ3tn(Z*xsSgFjPtH2s(zdXmmCM5ynV%#2tevEmwf9np&
      -  JWT_ACCESS_TOKEN=wF5vAmPkhqpDFtmhZtbkW6aX^^zWCN!NVfHVPfwUUvq3UT(@QZt#G7EkpHh(m#jQ
      -  JWT_REFRESH_TOKEN=&vw&#N&7V3&m#I775+gQvMLES!pu)bWwzr&%F2TPMMzxd4jV3aT(^HZXRZpGdIK%

      -  CLIENT_URL=http://localhost:3000
      -  REDIS_HOST=redisdb
      -  REDIS_PORT=6379
      -  REDIS_URL=redis://redisdb:6379
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb
      - redisdb
    networks:
      - common
  
  chatchatbe: 
    restart: always
    depends_on:
      - mysqldb
      - redisdb
    build: 
      context: ./chatService
      dockerfile: dockerfile.node
    image: trankhoi/chatapp-sernstack:chatchatbe
    environment:
      -  MYSQL_HOST=mysqldb
      -  MYSQL_PORT=3306
      -  NODE_ENV=development
      -  PORT = 5001

      -  JWT_ACTIVE_TOKEN=)@n!ZE3AD6g$q&m7%KUXZ3tn(Z*xsSgFjPtH2s(zdXmmCM5ynV%#2tevEmwf9np&
      -  JWT_ACCESS_TOKEN=wF5vAmPkhqpDFtmhZtbkW6aX^^zWCN!NVfHVPfwUUvq3UT(@QZt#G7EkpHh(m#jQ
      -  JWT_REFRESH_TOKEN=&vw&#N&7V3&m#I775+gQvMLES!pu)bWwzr&%F2TPMMzxd4jV3aT(^HZXRZpGdIK%

      -  CLIENT_URL=http://localhost:3000
      -  REDIS_HOST=redisdb
      -  REDIS_PORT=6379
      -  REDIS_URL=redis://redisdb:6379
    ports:
      - "5001:5001"
    networks:
      - common

  chatmessagebe: 
    restart: always
    build: 
      context: ./messageService
      dockerfile: dockerfile.node
    image: trankhoi/chatapp-sernstack:chatmessagebe
    environment:
      -  MYSQL_HOST=mysqldb
      -  MYSQL_PORT=3306
      -  NODE_ENV=development
      -  PORT = 5002

      -  JWT_ACTIVE_TOKEN=)@n!ZE3AD6g$q&m7%KUXZ3tn(Z*xsSgFjPtH2s(zdXmmCM5ynV%#2tevEmwf9np&
      -  JWT_ACCESS_TOKEN=wF5vAmPkhqpDFtmhZtbkW6aX^^zWCN!NVfHVPfwUUvq3UT(@QZt#G7EkpHh(m#jQ
      -  JWT_REFRESH_TOKEN=&vw&#N&7V3&m#I775+gQvMLES!pu)bWwzr&%F2TPMMzxd4jV3aT(^HZXRZpGdIK%

      -  CLIENT_URL=http://localhost:3000
      -  REDIS_HOST=redisdb
      -  REDIS_PORT=6379
      -  REDIS_URL=redis://redisdb:6379
    ports:
      - "5002:5002"
    depends_on:
      - mysqldb
      - redisdb
    networks:
      - common

  mysqldb: 
    container_name: mysqldb
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
       MY_ROOT_PASSWORD: null 
       MYSQL_PASSWORD: null
    networks:
      - common
  
  nginx: 
    restart: always
    build: 
      context: ./nginx
      dockerfile: dockerfile
    image: trankhoi/chatapp-sernstack:chatnginx
    depends_on:
      - chatmessagebe
      - chatchatbe
      - chatuserbe
    ports:
      - "80:80"
    networks:
      - common
  
  redisdb:
    image: redis:alpine
    restart: always
    networks:
      - common
    ports:
      - 6379:6379
    volumes:
      - cache:/data/db
      
networks:
  common:

volumes:
  db:
  cache: 